'use strict';

var verbs_ichidan = [
  new Term(['あ','ける'], ['開',''], 'to open'),
  new Term(['あげる'], [''], 'to give'),
  new Term(['あつ','める'], ['集',''], 'to gather; to collect'),
  new Term(['あ','びる'], ['浴',''], 'to bathe; to take a shower'),
  new Term(['あわ','てる'], ['慌',''], 'to panic; to be flustered'),
  new Term(['い','い','つ','ける'], ['言','','付',''], 'to command; to order; to tell on someone'),
  new Term(['い','きる'], ['生',''], 'to be alive'),
  new Term(['いじ','める'], ['虐',''], 'to torment; to bully'),
  new Term(['いまし','める'], ['戒',''], 'to admonish'),
  new Term(['い','る'], ['居',''], 'to exist; to be'),
  new Term(['い','れる'], ['入',''], 'to insert; to put in'),
  new Term(['う','まれる'], ['生',''], 'to be born'),
  new Term(['え','る'], ['得',''], 'to obtain; to get'),
  new Term(['お','きる'], ['起',''], 'to wake up; to occur'),
  new Term(['おく','れる'], ['遅',''], 'to be late; to lag behind'),
  new Term(['おさ','える'], ['抑',''], 'to restrain; to control'),
  new Term(['おし','える'], ['教',''], 'to teach; to inform'),
  new Term(['おそ','れる'], ['恐',''],  'to fear'),
  new Term(['お','ちる'], ['落',''], 'to fall; to fail'),
  new Term(['おぼ','える'], ['覚',''], 'to remember; to learn'),
  new Term(['お','りる'], ['降',''], 'to alight, to descend'),
  new Term(['お','れる'], ['折',''], 'to be broken; to snap'),
  new Term(['か','える'], ['変',''], 'to change'),
  new Term(['か','える'], ['換',''], 'to change (clothes)'),
  new Term(['かか','える'], ['抱',''], 'to hold (in your arms), have'),
  new Term(['かか','げる'], ['掲',''], 'to raise (a flag); to hold up'),
  new Term(['かける'], [''], 'to hang; to call on the phone; to risk'),
  new Term(['かさ','ねる'], ['重',''], 'to pile up; to repeat'),
  new Term(['かじ','る'], ['齧',''], 'to gnaw; to nibble'),
  new Term(['かぞ','える'], ['数',''], 'to count'),
  new Term(['かた','づ','ける'], ['片','付','ける'], 'to finish; to tidy up'),
  new Term(['かた','める'], ['固',''], 'to strengthen; to harden'),
  new Term(['かま','える'], ['構',''], 'to set up; to prepare in advance'),
  new Term(['か','りる'], ['借',''], 'to borrow; to rent'),
  new Term(['か','れる'], ['枯',''],  'to wither'),
  new Term(['かんが','える'], ['考',''], 'to think'),
  new Term(['かん','じる'], ['感',''], 'to feel; to sense'),
  new Term(['き','える'], ['消',''], 'to vanish; to disappear; to be extinguished'),
  new Term(['き','こえる'], ['聞',''], 'to be audible; to be able to hear'),
  new Term(['きず','つける'], ['傷',''], 'to wound; to damage; to harm'),
  new Term(['き','める'], ['決',''], 'to decide'),
  new Term(['き','る'], ['着',''], 'to wear'),
  new Term(['き','れる'], ['切',''], 'to break; to cut off; to expire'),
  new Term(['きん','じる'], ['禁',''], 'to ban; to prohibit'),
  new Term(['くず','れる'], ['崩',''], 'to collapse; to cave in'),
  new Term(['くら','べる'], ['比',''], 'to compare'),
  new Term(['くる','しめる'], ['苦',''], 'to inflict pain; to torment'),
  new Term(['く','れる'], ['呉',''], 'to give'),
  new Term(['く','れる'], ['暮',''], 'to grow dark (at night)'),
  new Term(['くわ','える'], ['加',''], 'to add to; to include'),
  new Term(['くわだ','てる'], ['企',''], 'to plan; to scheme'),
  new Term(['こ','げる'], ['焦',''], 'to be burned; to become charred'),
  new Term(['こし','か','ける'], ['腰','掛',''], 'to sit (western style)'),
  new Term(['こしら','える'], ['拵',''], 'to make; to manufacture'),
  new Term(['こた','える'], ['答',''], 'to answer'),
  new Term(['こぼれる'], [''], 'to spill; to overflow'),
  new Term(['こわ','れる'], ['壊',''], 'to break'),
  new Term(['さ','ける'], ['避',''], 'to avoid; to dodge'),
  new Term(['さ','げる'], ['下',''], 'to lower; to hang'),
  new Term(['ささ','える'], ['支',''], 'to support'),
  new Term(['さだ','める'], ['定',''], 'to decide; to establish'),
  new Term(['さまた','げる'], ['妨',''], 'to hinder; to obstruct'),
  new Term(['し','める'], ['閉',''], 'to shut'),
  new Term(['し','らせる'], ['知',''], 'to notify'),
  new Term(['しら','べる'], ['調',''], 'to check; to investigate'),
  new Term(['しん','じる'], ['信',''], 'to believe; to trust'),
  new Term(['す','ぎる'], ['過',''], 'to pass; to exceed'),
  new Term(['すぐ','れる'], ['優',''], 'to excel; to be superior'),
  new Term(['す','てる'], ['捨',''], 'to discard; to throw away'),
  new Term(['そだ','てる'], ['育',''], 'to raise (a child); to rear'),
  new Term(['たお','れる'], ['倒',''], 'to fall down; to collapse'),
  new Term(['たくわ','える'], ['蓄',''], 'to set aside; to store'),
  new Term(['たす','ける'], ['助',''], 'to help'),
  new Term(['た','てる'], ['立',''], 'to build'),
  new Term(['た','べる'], ['食',''], 'to eat'),
  new Term(['た','める'], ['貯',''], 'to save; to accumulate'),
  new Term(['た','りる'], ['足',''], 'to suffice; to be enough'),
  new Term(['つか','れる'], ['疲',''], 'to become tired'),
  new Term(['つ','ける'], ['点',''], 'to turn on; to light'),
  new Term(['つづ','ける'], ['続',''], 'to continue; to proceed'),
  new Term(['つと','める'], ['勤',''], 'to work for'),
  new Term(['つよ','める'], ['強',''], 'to strengthen'),
  new Term(['つ','れる'], ['連',''], 'to lead'),
  new Term(['で','かける'], ['出',''], 'to go out; to leave the house'),
  new Term(['で','き','る'], ['出','来',''], 'to be able'),
  new Term(['で','る'], ['出',''], 'to leave; to come out'),
  new Term(['と','める'], ['止',''], 'to stop; to cease'),
  new Term(['と','り','か','える'], ['取','','換',''], 'to exchange; to replace'),
  new Term(['と','れる'], ['取',''], 'to come off; to be removed'),
  new Term(['なが','める'], ['眺',''], 'to watch; to view'),
  new Term(['なが','れる'], ['流',''], 'to flow'),
  new Term(['なぐさ','める'], ['慰',''], 'to comfort; to console'),
  new Term(['な','げる'], ['投',''], 'to throw; to cast away'),
  new Term(['なま','ける'], ['怠',''], 'to be idle; to laze'),
  new Term(['な','める'], ['舐',''], 'to lick'),
  new Term(['なら','べる'], ['並',''], 'to line up'),
  new Term(['な','れる'], ['慣',''], 'to get used to; to grow accustomed to'),
  new Term(['に','げる'], ['逃',''],  'to run away; to escape'),
  new Term(['に','る'], ['似',''], 'to resemble; to be similar to'),
  new Term(['ぬ','れる'], ['濡',''], 'to become wet'),
  new Term(['ね','る'], ['寝',''], 'to sleep; to go to bed'),
  new Term(['の','せる'], ['載',''], 'to place on top'),
  new Term(['の','り','か','える'], ['乗','','換',''], 'to transfer (as in public transportation)'),
  new Term(['はじ','める'], ['始',''], 'to begin'),
  new Term(['はず','れる'], ['外',''], 'to be disconnected; to get out of place'),
  new Term(['は','れる'], ['晴',''], 'to become sunny; to clear up (as in weather)'),
  new Term(['ひ','き','う','ける'], ['引','','受',''], 'to undertake; to take over'),
  new Term(['ひろ','める'], ['広',''], 'to propagate; to disseminate'),
  new Term(['ふ','える'], ['増',''], 'to increase'),
  new Term(['ふ','せる'], ['伏',''], 'to lie face down'),
  new Term(['ふ','れる'], ['触',''], 'to touch'),
  new Term(['ぶつける'], [''], 'to hit; to run into'),
  new Term(['へ','る'], ['減',''], 'to decrease; to decline'),
  new Term(['ほど','ける'], ['解',''],  'to come untied; to loosen'),
  new Term(['ほ','める'], ['褒',''], 'to praise'),
  new Term(['ほ','れる'], ['惚',''], 'to fall in love; to be charmed'),
  new Term(['ま','ける'], ['負',''], 'to lose; to be defeated'),
  new Term(['ま','げる'], ['曲',''], 'to bend; to curve'),
  new Term(['ま','ぜる'], ['混',''],  'to mix'),
  new Term(['ま','ちが','える'], ['間','違',''], 'to make a mistake'),
  new Term(['み','える'], ['見',''], 'to be visible; to be able to see'),
  new Term(['み','せる'], ['見',''], 'to show'),
  new Term(['み','つける'], ['見',''], 'to find'),
  new Term(['みと','める'], ['認',''], 'to acknowledge; to admit; to recognize'),
  new Term(['み','る'], ['見',''], 'to look'),
  new Term(['むか','える'], ['迎',''], 'to go out to meet; to welcome'),
  new Term(['もう','ける'], ['儲',''], 'to profit; to make money'),
  new Term(['もてる'], [''], 'to be popular'),
  new Term(['もと','める'], ['求',''], 'to request; to ask; to seek'),
  new Term(['も','れる'], ['漏',''], 'to leak; to escape'),
  new Term(['や','ける'], ['焼',''], 'to burn'),
  new Term(['や','める'], ['辞',''], 'to stop; to give up; to resign'),
  new Term(['わか','れる'], ['別',''], 'to break up; to part from'),
  new Term(['わす','れる'], ['忘',''], 'to forget'),
];

var verbs_godan = [
  new Term(['あ','う'], ['会',''], 'to meet'),
  new Term(['あ','う'], ['合',''], 'to match; to fit'),
  new Term(['わら','う'], ['笑',''], 'to laugh')
];

var adjective_i = [
  new Term(['あお','い'], ['青',''], 'blue')
];

var adjective_na = [
  new Term(['す','き'], ['好'], 'like; love')
];
