'use strict';

// var verbs_ichidan = [
//   new Term(['あ','ける'], ['開',''], 'to open'),
//   new Term(['あげる'], [''], 'to give'),
//   new Term(['あつ','める'], ['集',''], 'to gather; to collect'),
//   new Term(['あ','びる'], ['浴',''], 'to bathe; to take a shower'),
//   new Term(['あわ','てる'], ['慌',''], 'to panic; to be flustered'),
//   new Term(['い','い','つ','ける'], ['言','','付',''], 'to command; to order; to tell on someone'),
//   new Term(['い','きる'], ['生',''], 'to be alive'),
//   new Term(['いじ','める'], ['虐',''], 'to torment; to bully'),
//   new Term(['いまし','める'], ['戒',''], 'to admonish'),
//   new Term(['い','る'], ['居',''], 'to exist; to be'),
//   new Term(['い','れる'], ['入',''], 'to insert; to put in'),
//   new Term(['う','まれる'], ['生',''], 'to be born'),
//   new Term(['え','る'], ['得',''], 'to obtain; to get'),
//   new Term(['お','きる'], ['起',''], 'to wake up; to occur'),
//   new Term(['おく','れる'], ['遅',''], 'to be late; to lag behind'),
//   new Term(['おさ','える'], ['抑',''], 'to restrain; to control'),
//   new Term(['おし','える'], ['教',''], 'to teach; to inform'),
//   new Term(['おそ','れる'], ['恐',''],  'to fear'),
//   new Term(['お','ちる'], ['落',''], 'to fall; to fail'),
//   new Term(['おぼ','える'], ['覚',''], 'to remember; to learn'),
//   new Term(['お','りる'], ['降',''], 'to alight, to descend'),
//   new Term(['お','れる'], ['折',''], 'to be broken; to snap'),
//   new Term(['か','える'], ['変',''], 'to change'),
//   new Term(['か','える'], ['換',''], 'to change (clothes)'),
//   new Term(['かか','える'], ['抱',''], 'to hold (in your arms), have'),
//   new Term(['かか','げる'], ['掲',''], 'to raise (a flag); to hold up'),
//   new Term(['かける'], [''], 'to hang; to call on the phone; to risk'),
//   new Term(['かさ','ねる'], ['重',''], 'to pile up; to repeat'),
//   new Term(['かじ','る'], ['齧',''], 'to gnaw; to nibble'),
//   new Term(['かぞ','える'], ['数',''], 'to count'),
//   new Term(['かた','づ','ける'], ['片','付','ける'], 'to finish; to tidy up'),
//   new Term(['かた','める'], ['固',''], 'to strengthen; to harden'),
//   new Term(['かま','える'], ['構',''], 'to set up; to prepare in advance'),
//   new Term(['か','りる'], ['借',''], 'to borrow; to rent'),
//   new Term(['か','れる'], ['枯',''],  'to wither'),
//   new Term(['かんが','える'], ['考',''], 'to think'),
//   new Term(['かん','じる'], ['感',''], 'to feel; to sense'),
//   new Term(['き','える'], ['消',''], 'to vanish; to disappear; to be extinguished'),
//   new Term(['き','こえる'], ['聞',''], 'to be audible; to be able to hear'),
//   new Term(['きず','つける'], ['傷',''], 'to wound; to damage; to harm'),
//   new Term(['き','める'], ['決',''], 'to decide'),
//   new Term(['き','る'], ['着',''], 'to wear'),
//   new Term(['き','れる'], ['切',''], 'to break; to cut off; to expire'),
//   new Term(['きん','じる'], ['禁',''], 'to ban; to prohibit'),
//   new Term(['くず','れる'], ['崩',''], 'to collapse; to cave in'),
//   new Term(['くら','べる'], ['比',''], 'to compare'),
//   new Term(['くる','しめる'], ['苦',''], 'to inflict pain; to torment'),
//   new Term(['く','れる'], ['呉',''], 'to give'),
//   new Term(['く','れる'], ['暮',''], 'to grow dark (at night)'),
//   new Term(['くわ','える'], ['加',''], 'to add to; to include'),
//   new Term(['くわだ','てる'], ['企',''], 'to plan; to scheme'),
//   new Term(['こ','げる'], ['焦',''], 'to be burned; to become charred'),
//   new Term(['こし','か','ける'], ['腰','掛',''], 'to sit (western style)'),
//   new Term(['こしら','える'], ['拵',''], 'to make; to manufacture'),
//   new Term(['こた','える'], ['答',''], 'to answer'),
//   new Term(['こぼれる'], [''], 'to spill; to overflow'),
//   new Term(['こわ','れる'], ['壊',''], 'to break'),
//   new Term(['さ','ける'], ['避',''], 'to avoid; to dodge'),
//   new Term(['さ','げる'], ['下',''], 'to lower; to hang'),
//   new Term(['ささ','える'], ['支',''], 'to support'),
//   new Term(['さだ','める'], ['定',''], 'to decide; to establish'),
//   new Term(['さまた','げる'], ['妨',''], 'to hinder; to obstruct'),
//   new Term(['し','める'], ['閉',''], 'to shut'),
//   new Term(['し','らせる'], ['知',''], 'to notify'),
//   new Term(['しら','べる'], ['調',''], 'to check; to investigate'),
//   new Term(['しん','じる'], ['信',''], 'to believe; to trust'),
//   new Term(['す','ぎる'], ['過',''], 'to pass; to exceed'),
//   new Term(['すぐ','れる'], ['優',''], 'to excel; to be superior'),
//   new Term(['す','てる'], ['捨',''], 'to discard; to throw away'),
//   new Term(['そだ','てる'], ['育',''], 'to raise (a child); to rear'),
//   new Term(['たお','れる'], ['倒',''], 'to fall down; to collapse'),
//   new Term(['たくわ','える'], ['蓄',''], 'to set aside; to store'),
//   new Term(['たす','ける'], ['助',''], 'to help'),
//   new Term(['た','てる'], ['立',''], 'to build'),
//   new Term(['た','べる'], ['食',''], 'to eat'),
//   new Term(['た','める'], ['貯',''], 'to save; to accumulate'),
//   new Term(['た','りる'], ['足',''], 'to suffice; to be enough'),
//   new Term(['つか','れる'], ['疲',''], 'to become tired'),
//   new Term(['つ','ける'], ['点',''], 'to turn on; to light'),
//   new Term(['つづ','ける'], ['続',''], 'to continue; to proceed'),
//   new Term(['つと','める'], ['勤',''], 'to work for'),
//   new Term(['つよ','める'], ['強',''], 'to strengthen'),
//   new Term(['つ','れる'], ['連',''], 'to lead'),
//   new Term(['で','かける'], ['出',''], 'to go out; to leave the house'),
//   new Term(['で','き','る'], ['出','来',''], 'to be able'),
//   new Term(['で','る'], ['出',''], 'to leave; to come out'),
//   new Term(['と','める'], ['止',''], 'to stop; to cease'),
//   new Term(['と','り','か','える'], ['取','','換',''], 'to exchange; to replace'),
//   new Term(['と','れる'], ['取',''], 'to come off; to be removed'),
//   new Term(['なが','める'], ['眺',''], 'to watch; to view'),
//   new Term(['なが','れる'], ['流',''], 'to flow'),
//   new Term(['なぐさ','める'], ['慰',''], 'to comfort; to console'),
//   new Term(['な','げる'], ['投',''], 'to throw; to cast away'),
//   new Term(['なま','ける'], ['怠',''], 'to be idle; to laze'),
//   new Term(['な','める'], ['舐',''], 'to lick'),
//   new Term(['なら','べる'], ['並',''], 'to line up'),
//   new Term(['な','れる'], ['慣',''], 'to get used to; to grow accustomed to'),
//   new Term(['に','げる'], ['逃',''],  'to run away; to escape'),
//   new Term(['に','る'], ['似',''], 'to resemble; to be similar to'),
//   new Term(['ぬ','れる'], ['濡',''], 'to become wet'),
//   new Term(['ね','る'], ['寝',''], 'to sleep; to go to bed'),
//   new Term(['の','せる'], ['載',''], 'to place on top'),
//   new Term(['の','り','か','える'], ['乗','','換',''], 'to transfer (as in public transportation)'),
//   new Term(['はじ','める'], ['始',''], 'to begin'),
//   new Term(['はず','れる'], ['外',''], 'to be disconnected; to get out of place'),
//   new Term(['は','れる'], ['晴',''], 'to become sunny; to clear up (as in weather)'),
//   new Term(['ひ','き','う','ける'], ['引','','受',''], 'to undertake; to take over'),
//   new Term(['ひろ','める'], ['広',''], 'to propagate; to disseminate'),
//   new Term(['ふ','える'], ['増',''], 'to increase'),
//   new Term(['ふ','せる'], ['伏',''], 'to lie face down'),
//   new Term(['ふ','れる'], ['触',''], 'to touch'),
//   new Term(['ぶつける'], [''], 'to hit; to run into'),
//   new Term(['へ','る'], ['減',''], 'to decrease; to decline'),
//   new Term(['ほど','ける'], ['解',''],  'to come untied; to loosen'),
//   new Term(['ほ','める'], ['褒',''], 'to praise'),
//   new Term(['ほ','れる'], ['惚',''], 'to fall in love; to be charmed'),
//   new Term(['ま','ける'], ['負',''], 'to lose; to be defeated'),
//   new Term(['ま','げる'], ['曲',''], 'to bend; to curve'),
//   new Term(['ま','ぜる'], ['混',''],  'to mix'),
//   new Term(['ま','ちが','える'], ['間','違',''], 'to make a mistake'),
//   new Term(['み','える'], ['見',''], 'to be visible; to be able to see'),
//   new Term(['み','せる'], ['見',''], 'to show'),
//   new Term(['み','つける'], ['見',''], 'to find'),
//   new Term(['みと','める'], ['認',''], 'to acknowledge; to admit; to recognize'),
//   new Term(['み','る'], ['見',''], 'to look'),
//   new Term(['むか','える'], ['迎',''], 'to go out to meet; to welcome'),
//   new Term(['もう','ける'], ['儲',''], 'to profit; to make money'),
//   new Term(['もてる'], [''], 'to be popular'),
//   new Term(['もと','める'], ['求',''], 'to request; to ask; to seek'),
//   new Term(['も','れる'], ['漏',''], 'to leak; to escape'),
//   new Term(['や','ける'], ['焼',''], 'to burn'),
//   new Term(['や','める'], ['辞',''], 'to stop; to give up; to resign'),
//   new Term(['わか','れる'], ['別',''], 'to break up; to part from'),
//   new Term(['わす','れる'], ['忘',''], 'to forget'),
// ];

var verbs_godan = [
  new Term(['あ','う'], ['会',''], 'to meet'),
  new Term(['あ','う'], ['合',''], 'to match; to fit'),
  new Term(['あお','ぐ'], ['仰',''], 'to look up; to seek'),
  new Term(['あ','がる'], ['上',''], 'to go up; to rise'),
  new Term(['あ','く'], ['開',''], 'to open; to become vacant'),
  new Term(['あせ','る'], ['焦',''], 'to be impatient; to be in a hurry'),
  new Term(['あそ','ぶ'], ['遊',''], 'to play'),
  new Term(['あたた','まる'], ['暖',''], 'to warm up'),
  new Term(['あつ','まる'], ['集',''], 'to gather; to assemble'),
  new Term(['あぶら','ぎる'], ['脂',''], 'to become greasy; to become oily'),
  new Term(['あら','う'], ['洗',''], 'to wash'),
  new Term(['ある','く'], ['歩',''], 'to walk'),
  new Term(['い','い','あらわ','す'], ['言','','表',''], 'to express (in words); to describe'),
  new Term(['い','い','か','える'], ['言','','換',''], 'to say in other words; to rephrase'),
  new Term(['い','い','だ','す'], ['言','','出',''], 'to start talking; to break the ice'),
  new Term(['い','いふらす'], ['言',''], 'to spread a rumor; to talk about'),
  new Term(['い','う'], ['言',''], 'to say'),
  new Term(['い','く'], ['行',''], 'to go'),
  new Term(['いそ','ぐ'], ['急',''], 'to hurry'),
  new Term(['いた','む'], ['痛',''], 'to hurt; to be injured'),
  new Term(['いつわ','る'], ['偽',''], 'to lie; to cheat; to deceive'),

  new Term(['いの','る'], ['祈',''], 'to pray; to wish for'),
  new Term(['い','ば','る'], ['威','張',''], 'to boast; to swagger'),
  new Term(['いや','がる'], ['嫌',''], 'to dislike; to hate'),
  new Term(['い','る'], ['要',''], 'to need'),
  new Term(['いわ','う'], ['祝',''], 'to celebrate; to congratulate'),
  new Term(['うご','く'], ['動',''], 'to move'),
  new Term(['うしな','う'], ['失',''], 'to lose; to part with'),
  new Term(['うた','う'], ['歌',''], 'to sing'),
  new Term(['う','る'], ['売',''], 'to sell'),
  new Term(['えら','ぶ'], ['選',''], 'to choose; to select'),
  new Term(['お','う'], ['追',''], 'to chase; to run after'),
  new Term(['お','く'], ['置',''], 'to put; to place'),
  new Term(['おく','る'], ['送',''], 'to send; to ship'),
  new Term(['お','こす'], ['起',''], 'to awaken (someone); to cause; to bring about'),
  new Term(['おこ','る'], ['怒',''], 'to get angry'),
  new Term(['お','こる'], ['起',''], 'to occur; to happen'),
  new Term(['お','しむ'], ['惜',''], 'to regret'),
  new Term(['お',''], ['押',''], 'to push; to press'),
  new Term(['おそ','う'], ['襲',''], 'to attack'),
  new Term(['お','とす'], ['落',''], 'to drop; to let fall'),
  new Term(['おと','る'], ['劣',''], 'to be inferior; to fall behind'),
  new Term(['おど','る'], ['踊',''], 'to dance'),
  new Term(['おどろ','く'], ['驚',''], 'to be suprised; to be amazed'),
  new Term(['おも','いつく'], ['思',''], 'to conceive; to come up with'),
  new Term(['おも','う'], ['思',''], 'to think'),
  new Term(['およ','ぐ'], ['泳',''], 'to swim'),
  new Term(['およ','ぶ'], ['及',''], 'to extend; to reach'),

  new Term(['お','わる'], ['終',''], 'to end; to finish'),
  new Term(['か','う'], ['買',''], 'to buy'),
  new Term(['か','う'], ['飼',''], 'to keep (a pet); to raise; to rear'),
  new Term(['かえ','す'], ['返',''], 'to give back; to return (something to someone)'),
  new Term(['かえ','る'], ['帰',''], 'to return (home)'),
  new Term(['か','かる'], ['掛',''], 'to take (a resource, e.g. time, money); to hang'),
  new Term(['かか','わる'], ['関',''], 'to be involved with; to concern oneself with'),
  new Term(['かがや','く'], ['輝',''], 'to shine; to sparkle'),
  new Term(['かぎ','る'], ['限',''], 'to limit'),
  new Term(['か','く'], ['書',''], 'to write'),
  new Term(['かく','す'], ['隠',''], 'to hide (something)'),
  new Term(['かく','れる'], ['隠',''], 'to hide (oneself)'),
  new Term(['かこ','む'], ['囲',''], 'to surround; to enclose'),
  new Term(['かさ','なる'], ['重',''], 'to overlap; to be piled up'),
  new Term(['かざ','る'], ['飾',''], 'to decorate; to display'),
  new Term(['か','す'], ['貸',''], 'to lend'),
  new Term(['かす','む'], ['霞',''], 'to grow hazy; to be misty'),
  new Term(['かせ','ぐ'], ['稼',''], 'to make money; to earn a living'),
  new Term(['かた','まる'], ['固',''], 'to harden; to solidify'),
  new Term(['かたむ','く'], ['傾',''], 'to lean towards; to tilt'),
  new Term(['か','つ'], ['勝',''], 'to win'),
  new Term(['かつ','ぐ'], ['担',''], 'to carry on one\'s shoulders'),
  new Term(['かな','う'], ['適',''], 'to be suited'),
  new Term(['かな','しむ'], ['悲',''], 'to be sad; to grieve'),
  new Term(['かば','う'], ['庇',''], 'to protect; to stick up for'),
  new Term(['かぶ','る'], ['被',''], 'to wear (on one\'s head)'),
  new Term(['かま','う'], ['構',''], 'to care about; to mind'),
  new Term(['か','む'], ['噛',''], 'to bite'),
  new Term(['かよ','う'], ['通',''], 'to commute'),
  new Term(['からかう'], [''], 'to tease; to mock'),
  new Term(['かわい','がる'], ['可愛',''], 'to be affectionate; to be fond of'),
  new Term(['かわ','かす'], ['乾',''], 'to dry; to dehydrate'),
  new Term(['かわ','く'], ['乾',''], 'to become dry'),
  new Term(['か','わる'], ['変',''], 'to change'),
  new Term(['がん','ば','る'], ['頑','張',''], 'to try one\'s best; to work hard'),
  new Term(['き','く'], ['聞',''], 'to listen'),
  new Term(['き','づか','う'], ['気','遣',''], 'to worry about; to consider'),
  new Term(['き','づ','く'], ['気','付',''], 'to sense; to notice; to realize'),
  new Term(['き','まる'], ['決',''], 'to be decided'),
  new Term(['き','る'], ['切',''], 'to cut'),
  new Term(['く','い','ちが','う'], ['食','','違',''], 'to differ; to clash'),
  new Term(['くさ','る'], ['腐',''], 'to decay; to go bad'),
  new Term(['くず','す'], ['崩',''], 'to destroy; to break down'),
  new Term(['くだ','く'], ['砕',''], 'to crush; to smash'),
  new Term(['く','ど','く'], ['口','説',''], 'to seduce; to make a play'),
  new Term(['く','む'], ['組',''], 'to put together; to assemble'),
  new Term(['くも','る'], ['曇',''], 'to become cloudy'),
  new Term(['く','らす'], ['暮',''], 'to live; to get along'),
  new Term(['くら','む'], ['眩',''], 'to be dazzled by; to be dizzied by'),
  new Term(['く','り','か','えす'], ['繰','','返',''], 'to repeat'),
  new Term(['くる','う'], ['狂',''], 'to go mad; to be out of order'),
  new Term(['くる','しむ'], ['苦',''], 'to suffer'),
  new Term(['け','す'], ['消',''], 'to erase; to turn off'),
  new Term(['け','る'], ['蹴',''], 'to kick'),
  new Term(['こころざ','す'], ['志',''], 'to aspire to'),
  new Term(['こ','す'], ['越','す'], 'to go across; to go over; to pass time'),

  new Term(['こと','なる'], ['異',''], 'to differ from'),
  new Term(['こと','わる'], ['断',''], 'to refuse; to decline'),
  new Term(['この','む'], ['好',''], 'to like; to prefer'),

  // TODO(andrea): finish porting godan
  // new Term(['こぼす', null, null, 'to spill'),
  // new Term(['こまる'], ['困る'], 'to be in trouble'),
  // new Term(['こむ'], ['込む'], 'to become crowded'),
  // new Term(['こらす'], ['凝らす'], 'to concentrate'),
  // new Term(['ころす'], ['殺す'], 'to kill'),
  // new Term(['ころぶ'], ['転ぶ'], 'to fall down'),
  // new Term(['こわがる'], ['怖がる'], 'to fear'),
  // new Term(['こわす'], ['壊す'], 'to smash'),
  // new Term(['さがす'], ['探す'], 'to search for'),
  // new Term(['さがる'], ['下がる'], ['to fall, drop, hang'),
  // new Term(['さく'], ['咲く'], ['to bloom'),
  // new Term(['さす'], ['刺す'], 'to point out, sting, stab'),
  // new Term(['さそう'], ['誘う'], ['to invite, tempt'),
  // new Term(['さわぐ'], ['騒ぐ'], ['to make a noise, be rowdy'),
  // new Term(['さわる'], ['触る'], ['to touch or feel (with hands)'),
  // new Term(['しかる'], ['叱る'], ['to scold, tell off'),
  // new Term(['しく'], ['敷く'], ['to spread out, lay'),
  // new Term(['しずまる'], ['静まる'], 'to grow quiet'),
  // new Term(['しずむ'], ['沈む'], 'to feel depressed, sink'),
  // new Term(['しぬ'], ['死ぬ'], 'to die'),
  // new Term(['しばる'], ['縛る'], 'to tie up, bind'),
  // new Term(['しまう', null, null, 'to put away'),
  // new Term(['しまる'], ['閉まる'], 'to close, be closed'),
  // new Term(['しめす'], ['示す'], 'to indicate, point out'),
  // new Term(['しゃべる'], ['喋る'], 'to chatter'),
  // new Term(['しる'], ['知る'], 'to know'),
  // new Term(['じゅくす'], ['熟す'], 'to mature, ripen'),
  // new Term(['すう'], ['吸う'], 'to inhale, sip, smoke'),
  // new Term(['すく'], ['空く'], 'to become empty, uncrowded'),
  // new Term(['すくう'], ['救う'], 'to rescue, save'),
  // new Term(['すすむ'], ['進む'], 'to go forward, advance'),
  // new Term(['すべる'], ['滑る'], 'to slip'),
  // new Term(['すむ'], ['住む'], 'to live, reside'),
  // new Term(['すわる'], ['座る'], 'to sit'),
  // new Term(['そだつ'], ['育つ'], 'to grow up, be raised'),
  // new Term(['たおす'], ['倒す'], 'to overthrow, knock down'),
  // new Term(['たくらむ'], ['企む'], 'to plot, scheme'),
  // new Term(['たける'], ['猛る'], 'to act violently'),
  // new Term(['たす'], ['足す'], 'to add'),
  // new Term(['たたむ'], ['畳む'], 'to fold'),
  // new Term(['たつ'], ['立つ'], 'to stand up'),
  // new Term(['たのしむ'], ['楽しむ'], 'to enjoy, have fun'),
  // new Term(['たのむ'], ['頼む'], 'to request, order, ask favour'),
  // new Term(['たまる'], ['貯める'], 'to be saved, accumulated'),
  // new Term(['ためす'], ['試す'], 'to test, try, taste'),
  // new Term(['だく'], ['抱く'], 'to embrace, hug'),
  // new Term(['だす'], '出す'], ['to extract, take out'),
  // new Term(['だます'], ['騙す'], 'to trick'),
  // new Term(['だまる'], ['黙る'], 'to stop talking'),
  // new Term(['ちがう'], ['違う'], 'to be different, wrong'),
  // new Term(['ちる'], ['散る'], 'to fall, scatter'),
  // new Term(['つかう'], ['使う'], 'to use, operate'),
  // new Term(['つく'], ['着く'], 'to arrive'),
  // new Term(['つくる'], ['作る'], 'to make, build, create'),
  // new Term(['つぐ'], ['次ぐ'], 'to be next'),
  // new Term(['つつむ'], ['包む'], 'to wrap'),
  // new Term(['つづく'], ['続く'], 'to continue, follow'),
  // new Term(['つよまる'], ['強まる'], 'to become stronger'),
  // new Term(['つる'], ['釣る'], 'to fish'),
  // new Term(['てつだう'], ['手伝う'], 'to help'),
  // new Term(['とどく'], ['届く'], 'to reach'),
  // new Term(['とぶ'], ['飛ぶ'], 'to jump, fly'),
  // new Term(['とまる'], ['止まる'], 'to stop'),
  // new Term(['とる'], ['取る'], 'to take, steal'),
  // new Term(['どじる', null, null, 'to mess up'),
  // new Term(['なおす'], ['直す'], 'to repair, cure'),
  // new Term(['なおる'], ['治る'], 'to be cured, healed'),
  // new Term(['ながす'], '流す'], 'to pour, let flow'),
  // new Term(['なく'], ['鳴く'], 'to cry'),
  // new Term(['なくす'], ['無くす'], 'to lose, remove'),
  // new Term(['なくなる'], ['無くなる'], 'to be missing, vanish'),
  // new Term(['なぐる'], ['殴る'], 'to punch, hit'),
  // new Term(['なじむ'], ['馴染む'], 'to get used to, adapt to'),
  // new Term(['ならう'], ['習う'], 'to learn'),
  // new Term(['ならぶ'], ['並ぶ'], 'to form a line, equal'),
  // new Term(['なる'], ['成る'], 'to become'),
  // new Term(['にぎる'], ['握る'], 'to grasp'),
  // new Term(['にらむ'], ['睨む'], 'to glare at, keep an eye on'),
  // new Term(['ぬぐ'], ['脱ぐ'], 'to remove'),
  // new Term(['ぬぐ'], ['脱ぐ'], 'to take off, remove (shoes, clothes)'),
  // new Term(['ぬすむ'], ['盗む'], 'to steal'),
  // new Term(['ぬる'], ['塗る'], 'to paint'),
  // new Term(['ぬる'], ['塗る'], 'to smear on'),
  // new Term(['ねじる'], ['捩じる'], 'to twist'),
  // new Term(['ねむる'], ['眠る'], 'to fall asleep'),
  // new Term(['のこす'], ['残す'], 'to leave behind, save'),
  // new Term(['のこる'], ['残る'], 'to left over, remain'),
  // new Term(['ののしる'], ['罵る'], 'to abuse verbally, curse'),
  // new Term(['のばす'], ['延ばす'], 'to postpone, extend'),
  // new Term(['のぼる'], ['登る'], 'to climb'),
  // new Term(['のむ'], ['飲む'], 'to drink'),
  // new Term(['のる'], ['乗る'], 'to board, ride on'),
  // new Term(['はいる'], ['入る'], 'to enter'),
  // new Term(['はく'], ['履く'], 'to put on, wear (on feet or legs - trousers/shoes etc)'),
  // new Term(['はげます'], ['励ます'], 'to encourage'),
  // new Term(['はげむ'], ['励む'], 'to strive, make every effort'),
  // new Term(['はこぶ'], ['運ぶ'], 'to carry'),
  // new Term(['はさむ'], ['挟む'], 'to catch, hold (between two things)'),
  // new Term(['はしる'], ['走る'], 'to run'),
  // new Term(['はじまる'], ['始まる'], 'to begin'),
  // new Term(['はずす'], ['外す'], 'to remove, unfasten'),
  // new Term(['はたらく'], ['働く'], 'to work'),
  // new Term(['はなしあう'], ['話し合う'], 'to Discuss'),
  // new Term(['はなす'], ['話す'], 'to speak'),
  // new Term(['はなれる'], ['離れる'], 'to separate from, leave'),
  // new Term(['はべる'], ['侍る'], 'to attend on'),
  // new Term(['はやる'], ['流行る'], 'to become popular'),
  // new Term(['はらう'], ['払う'], 'to pay'),
  // new Term(['はる'], ['張る'], 'to stick, put something on'),
  // new Term(['ひかる'], ['光る'], 'to shine, glitter'),
  // new Term(['ひく'], ['引く'], 'to pull'),
  // new Term(['ひく'], ['弾く'], 'to play (string instrument)'),
  // new Term(['ひねる'], ['捻る'], 'to bend, twist'),
  // new Term(['ひやかす'], ['冷やかす'], 'to tease, make fun of'),
  // new Term(['ひやす'], ['冷やす'], 'to cool, refridgerate'),
  // new Term(['ひらく'], ['開く'], 'to open, hold (an event, party etc)'),
  // new Term(['ひろう'], ['拾う'], 'to pick up, find'),
  // new Term(['ひろまる'], ['広まる'], 'to spread, become popular'),
  // new Term(['びびる', null, null, 'to be suprised'),
  // new Term(['ふく'], ['吹く'], 'to blow, wipe'),
  // new Term(['ふける', null, null, 'to be absorbed in'),
  // new Term(['ふせる'], ['臥せる'], 'to lie down'),
  // new Term(['ふとる'], ['太る'], 'to get fat, put on weight'),
  // new Term(['ふむ'], ['踏む'], 'to step on'),
  // new Term(['ふる'], ['降る'], 'to fall from the sky'),
  // new Term(['ぶつかる', null, null, 'to hit, collide with, clash'),
  // new Term(['へらす'], ['減らす'], 'to reduce, decrease'),
  // new Term(['へる'], ['減る'], 'to decrease, reduce'),
  // new Term(['ほしがる'], ['欲しがる'], 'to want, desire'),
  // new Term(['ほす'], ['干す'], 'to dry, air'),
  // new Term(['ほどく'], ['解く'], 'to untie'),
  // new Term(['ほのめかす'], ['仄めかす'], 'to hint'),
  // new Term(['ほる'], ['掘る'], 'to dig'),
  // new Term(['ほろびる'], ['滅びる'], 'to perish'),
  // new Term(['ほろぼす'], ['滅ぼす'], 'to destroy, ruin'),
  // new Term(['まいる'], ['参る'], 'to come/go (humble)'),
  // new Term(['まかす'], ['負かす'], 'to defeat'),
  // new Term(['まがる'], ['曲がる'], 'to turn, bend'),
  // new Term(['まじる'], ['混じる'], 'to be mixed, get mingled with, join'),
  // new Term(['まちがう'], ['間違う'], 'to be mistaken, make a mistake'),
  // new Term(['まつ'], ['待つ'], 'to wait'),
  // new Term(['まつる'], ['祀る'], 'to worship'),
  // new Term(['まなぶ'], ['学ぶ'], 'to learn, study'),
  // new Term(['まねく'], ['招く'], 'to invite, beckon to'),
  // new Term(['まもる'], ['守る'], 'to protect'),
  // new Term(['まよう'], ['迷う'], 'to be puzzled'),
  // new Term(['まわる'], '回る'], ['to go round'),
  // new Term(['みがく'], ['磨く'], 'to polish'),
  // new Term(['みつかる'], ['見つかる'], 'to be found'),
  // new Term(['みなす'], ['見做す'], 'to look upon, consider'),
  // new Term(['みのがす'], ['見逃す'], 'to overlook, let pass'),
  // new Term(['みのる'], ['実る'], 'to ripen, bear fruit'),
  // new Term(['みはる'], ['見張る'], 'to stand guard, keep lookout'),
  // new Term(['むかう'], ['向かう'], 'to face, turn/head toward'),
  // new Term(['むすぶ'], ['結ぶ'], 'to tie, knot, make a contract'),
  // new Term(['めだつ'], ['目立つ'], 'to attract attention, stand out'),
  // new Term(['もうかる'], ['儲かる'], 'to be profitable, make money'),
  // new Term(['もつ'], ['持つ'], 'to have, hold, own'),
  // new Term(['もとづく'], ['基づく'], 'to be based on'),
  // new Term(['もどす'], ['戻す'], 'to return, put back, vomit'),
  // new Term(['もどる'], ['戻る'], 'to return, go back'),
  // new Term(['もらう'], ['貰う'], 'to receive, get'),
  // new Term(['もらす'], ['漏らす'], 'to leak, disclose'),
  // new Term(['やく'], ['焼く'], 'to bake, grill'),
  // new Term(['やすむ'], ['休む'], 'to rest, sleep'),
  // new Term(['やる', null, null, 'to do, give'),
  // new Term(['よぶ'], ['呼ぶ'], 'to call'),
  // new Term(['よむ'], ['読む'], 'to read'),
  // new Term(['よろこぶ'], ['喜ぶ'], 'to be glad, pleased'),
  // new Term(['わかる'], ['分かる'], 'to understand'),
  // new Term(['わたす'], '渡す'], ['to hand over'),
  // new Term(['わたる'], '渡る'], ['to cross'),
  // new Term(['わらう'], '笑う'], ['to laugh'),
];

var adjective_i = [
  new Term(['あお','い'], ['青',''], 'blue')
];

var adjective_na = [
  new Term(['す','き'], ['好'], ['like; love')
];
